### ISSUE TITLE
Bug Report - Failure to Recognize Consecutive Guitar Techniques

### ISSUE THREAD

**Issue by Anselmo21** [MaishaRahman98/demo2311#10]
Category | Detail |
-|-
Bug Reported by | Rafael Dolores 
Error Name |  Failure to Recognize Consecutive Guitar Techniques
Error Description |  The application will only recognize and display the first technique in a chain of hammer-ons and pull-offs. That is, suppose there is a hammer-on prior to a pull-off technique. In the generated musicXML file, only the hammer-on tag will be displayed and the pull-off will be disregarded  
Steps to Reproduce | 1. Run application. <br/>  2. Press open.<br/>  3. Choose any guitar tablature([SampleTab.txt](https://github.com/MaishaRahman98/demo2311/files/6197581/SampleTab.txt) is the tab used for this specific test) .<br/>  4. Press translate.
Expected Result | For [SampleTab.txt](https://github.com/MaishaRahman98/demo2311/files/6197581/SampleTab.txt), the notes within the chain of techniques should have a corresponding hammer-on or pull-off tag to indicate when the technique began or ended: ![image](https://user-images.githubusercontent.com/77305767/112320041-05285380-8c85-11eb-92cd-1fdffad33f0d.png)
Actual Result | No tag was allocated to denote the occurrence of the hammer-on technique in [SampleTab.txt](https://github.com/MaishaRahman98/demo2311/files/6197670/SampleTab.txt)(go to the highlighted sections to see where it's missing): ![image](https://user-images.githubusercontent.com/77305767/112321006-ed050400-8c85-11eb-85e2-f4e5867cbc9b.png)
Machine/Version | Windows 10, Eclipse Gradle Build, Latest Commit on Master Branch(id a0abf6c)
Priority | Low Priority, Does not affect major workflows.
Severity| Low Severity, Not very impactful and only occurs when techniques are present.

**Comment by nugea** [comment]
Issue fixed.
