### ISSUE TITLE
Bug Report - Incorrect Partitions of Measure in Drum Tablatures

### ISSUE THREAD

**Issue by Anselmo21** [MaishaRahman98/demo2311#11]
Category | Detail |
-|-
Bug Reported by | Rafael Dolores 
Error Name |  Incorrect Partitions of Measure in Drum Tablatures with Appropriate Numbering
Error Description |  The application failed to recognize the respective measures of a drum tablature.
Steps to Reproduce | 1. Run application. <br/>  2. Press open.<br/>  3. Choose any drum tablature([DrumTabSAMPLE.txt](https://github.com/MaishaRahman98/demo2311/files/6198678/DrumTabSAMPLE.txt) is the tab used for this specific test) .<br/>  4. Press translate.
Expected Result | For [DrumTabSAMPLE.txt](https://github.com/MaishaRahman98/demo2311/files/6198678/DrumTabSAMPLE.txt), the corresponding musicXML file should contain two measure tags numbered as "1" and "2" where each measure contains the appropriate set of notes: ![image](https://user-images.githubusercontent.com/77305767/112324778-8550b800-8c89-11eb-9f6d-a7b81642f659.png) ![image](https://user-images.githubusercontent.com/77305767/112324893-9a2d4b80-8c89-11eb-8ec7-ac5519708e9a.png)
Actual Result | The first measure was numbered as "1" and it only contains the attribute section. Meanwhile, the second measure was labelled as "13" and all of the notes within the tablature were displayed on this measure. ![image](https://user-images.githubusercontent.com/77305767/112326116-a1088e00-8c8a-11eb-9574-0de7ffc0c17e.png)
Machine/Version | Windows 10, Eclipse Gradle Build, Latest Commit on Master Branch(id a0abf6c)
Priority | High Priority, Visible but not preventing users from completing the application's workflow.
Severity| Low Severity, Translation Process occurred but with some mistakes.

**Comment by MaishaRahman98** [comment]
@RafaelDolores Thanks for your bug report. I (@MaishaRahman98) will address this bug.

**Comment by MaishaRahman98** [comment]
Bug is fixed.
