### ISSUE TITLE
Bug report - No output from translating drum tablature

### ISSUE THREAD

**Issue by YUJunhyeongPark** [MaishaRahman98/demo2311#14]
Bug Raised By:
Junhyeong Park

Version:
Master – last commit id a0abf6c

Platform:
Windows 10 x64
Eclipse IDE for Java Developers - 2020 - 12

Description:
There is no output from the translation of a drum tablature

Details:
When interpreting an drum tablature, it is not showing any outputs.

Reproduction:

Run application
open drumTablature.txt
Click translate
Expected:
A output following the .musicxml format.

Actual:
No output from translation of the txt file

Priority:
1

Severity:
High

Screenshots:
Input:
image
![image](https://user-images.githubusercontent.com/77296784/112346130-09ac3680-8c9c-11eb-8ad3-eda01003b9fe.png)

Output:
![image](https://user-images.githubusercontent.com/77296784/112346168-12047180-8c9c-11eb-894e-f161b8337b9d.png)

Input file:
drumTablature.txt

**Comment by MaishaRahman98** [comment]
@YUJunhyeongPark Thanks for this bug report. @MaishaRahman98 will handle this bug.

**Comment by MaishaRahman98** [comment]
We are currently working on fixing this.
