### ISSUE TITLE
Resizing window

### ISSUE THREAD

**Issue by hiimangel** [MaishaRahman98/demo2311#15]
Bug Reported by: Alp Baran Sirek

Error name- Sizing of Elements of the GUI Fail to Resize According To The Ratio

Error Description- When the application window is resized by any amount, including full-screen mode of windows 10 (any other size than default window size at launch), the ratio of the boxes and elements fail to resize according to its ratio, resulting the text box to be mashed up with the background colour and two out of place black bars on top.
==Windowed==
![Capture](https://user-images.githubusercontent.com/71943217/112408789-a7702780-8cd5-11eb-9564-7258063162ca.PNG)
==Full-Screen==
![fullscreen](https://user-images.githubusercontent.com/71943217/112408794-a939eb00-8cd5-11eb-83c3-10cc53ee634a.PNG)

Machine/Version- Windows 10, Eclipse Gradle build

Reproduction
Run the application
Change the window size to any other

Priority-Low priority

Severity-Low severity

**Comment by Shawnli3287** [comment]
@hiimangel Thanks for this bug report. I (@Li-wenxuan-216374324 ) already fixed this bug.
