### ISSUE TITLE
Bug report - Improper spacing when converted to .musicxml format using the base format

### ISSUE THREAD

**Issue by YUJunhyeongPark** [MaishaRahman98/demo2311#16]
Bug Raised By:
Junhyeong Park

Version:
Master – last commit id a0abf6c

Platform:
Windows 10 x64
Eclipse IDE for Java Developers - 2020 - 12

Description:
Measure number is printed out with more spaces beforehand than the notes

Details:
Measure number after the first measure is printed out with more spaces beforehand than the child notes.

Reproduction:

Run application
open guitarTablature.txt
Click translate
Expected:
Measure numbers printed out with lesser space than the child notes

Actual:
Measure numbers other than the first one is printed with more spaces than their child notes.

Priority:
2

Severity:
Medium

Screenshots:
Input:
![image](https://user-images.githubusercontent.com/77296784/112351458-4f6afe00-8ca0-11eb-9319-6ec7d78f4cc4.png)

Output:
![image](https://user-images.githubusercontent.com/77296784/112351557-614ca100-8ca0-11eb-856f-bf6932414070.png)
![image](https://user-images.githubusercontent.com/77296784/112351626-6f022680-8ca0-11eb-8b65-dda58b456bfc.png)

Input file:
guitarTablature.txt

**Comment by MaishaRahman98** [comment]
@YUJunhyeongPark Thanks for this bug report. I (@MaishaRahman98) will handle this bug.

**Comment by MaishaRahman98** [comment]
Bug is fixed.
