### ISSUE TITLE
Resizing the window causes visual bug

### ISSUE THREAD

**Issue by arjitjohar** [MaishaRahman98/demo2311#17]
**Name:** Resizing the window causes visual bug
**Description:** when resizing the GUI, the color pallet breaks.
**Steps to reproduce:** 

1. open the project
2. expand the project to full screen

**Expected Result:** color pallet should remain the same.

**Actual Result:** color pallet  of the main input box bleeds into the rest of the GUI
![image](https://user-images.githubusercontent.com/46409539/112376829-53584980-8cbb-11eb-9634-87a37c4a3c08.png)

**screen recording:**

https://user-images.githubusercontent.com/46409539/112377137-c1047580-8cbb-11eb-9dc1-21a873257255.mp4

**Browser/version:** windows 10 x64, java11
**Priority:** low
**file used**:  N/A

**musicXML viewer used**: N/A

**Comment by Shawnli3287** [comment]
@arjitjohar Thanks for this bug report. I (@Li-wenxuan-216374324 ) already fixed this bug.
