### ISSUE TITLE
Palm Mute With Guitar Tab Bug

### ISSUE THREAD

**Issue by arjitjohar** [MaishaRahman98/demo2311#18]
**Name**: Palm Mute With Guitar Tab Bug
**Description**: When you input a guitar tab with a palm mute, it registers as a drum tab and does not output any notes.
**Steps to reproduce**:

1. open the project
2. input this file: [music.txt](https://github.com/MaishaRahman98/demo2311/files/6200871/music.txt) into the program
3. hit translate

**Actual Result**:
![image](https://user-images.githubusercontent.com/46409539/112393035-c8824980-8cd0-11eb-87b9-2d6b01a55b74.png)

[actual.txt](https://github.com/MaishaRahman98/demo2311/files/6200875/actual.txt)

**screen recording**:

https://user-images.githubusercontent.com/46409539/112393554-a63cfb80-8cd1-11eb-864e-396353358fd1.mp4

**Browser/version**: windows 10 x64, java11
**Priority**: medium
**file used**: [music.txt](https://github.com/MaishaRahman98/demo2311/files/6200911/music.txt)

**musicXML viewer used**:https://opensheetmusicdisplay.github.io/demo/

**Comment by nugea** [comment]
Palm mute is not a requirement.
