### ISSUE TITLE
Tapped Harmonics breaks program 

### ISSUE THREAD

**Issue by arjitjohar** [MaishaRahman98/demo2311#19]
**Name:** Tapped Harmonics breaks the program 
**Description:** when inputting a ASCII tab with a tapper harmonic, the program returns a music tab with no information
**Steps to reproduce:** 

1. open the project 
2.  input this [music.txt](https://github.com/MaishaRahman98/demo2311/files/6201008/music.txt)
3.  hit translate

**Expected Result:** 

![image](https://user-images.githubusercontent.com/46409539/112396419-80febc00-8cd6-11eb-9a71-5b2deb93d342.png)

**Actual Result:** returns an empty guitar music sheet
[actual.txt.txt](https://github.com/MaishaRahman98/demo2311/files/6201014/actual.txt.txt)

![image](https://user-images.githubusercontent.com/46409539/112396433-878d3380-8cd6-11eb-867a-43a39c4280b4.png)

**screen recording:**

https://user-images.githubusercontent.com/46409539/112396580-c4f1c100-8cd6-11eb-994d-81be3721d3d9.mp4

**Browser/version:** windows 10 x64, java11
**Priority:** high
**file used**: [music.txt](https://github.com/MaishaRahman98/demo2311/files/6201019/music.txt)

**musicXML viewer used**: https://opensheetmusicdisplay.github.io/demo/ and https://how-to-play-electric-guitar.net/tab-symbols.html

**Comment by nugea** [comment]
Tapped harmonics is not a requirement.
