### ISSUE TITLE
UI/Background Bugs When Resizing Window

### ISSUE THREAD

**Issue by dsantor9** [MaishaRahman98/demo2311#20]
Operating System: Windows 10 using Eclipse (Gradle)
Severity: Low – Only sometimes impacts functionality, and is easily fixed by the user
Priority: Moderate – Though mostly visual, it could make the program look/behave slightly less professionally

**Description:**
The program window’s background can be distorted in unintended ways based on how the window is resized. For example, when maximized, the background cannot reach the ends of the screen, and as a result, yellow bars appear on either side of the screen (letterboxing). Also, when dragging the ends of the window to make it either thinner or shorter, the black text box or left-side buttons can become cut off.

**How to Reproduce:**
In order to cause the window to display yellow bars, click the “Maximize” button (Windows). 

![Peer 2 Resize 1](https://user-images.githubusercontent.com/77293963/112403747-5b2ce380-8ce5-11eb-8faa-ad81fc837d43.png)

To cut off the buttons/text box by making the window shorter/thinner, hover the mouse cursor over the right or top edge of the window until it displays a two-sided arrow icon. Then, hold click and drag the cursor into the window. In this example image, the window was made both shorter and thinner in order to cut off both the buttons and text box respectively.

![Peer 2 Resize 2](https://user-images.githubusercontent.com/77293963/112403761-64b64b80-8ce5-11eb-98c4-03d55d9b60c4.png)

**Comment by Shawnli3287** [comment]
@dsantor9 Thanks for this bug report. I (@Li-wenxuan-216374324 ) already fixed this bug.
