### ISSUE TITLE
Bug Report 3/3: Resized GUI looks glitched.

### ISSUE THREAD

**Issue by mohful** [MaishaRahman98/demo2311#22]
Category | Detail |
-|-
Raised By | Mohammed Ahmed Fulwala
Error Title |  The GUI does not resize properly when the maximize button is clicked. This might stem because the dimensions of the pane used is fixed and is not flexible.
Version | Windows 10, JavaSE 15.0.2
Platform | Eclipse Gradle Build
Steps to Reproduce | 1. Click on the maximize button on the GUI
Expected Result | The GUI should maximize and should not look distorted
Actual Result | The GUI looks distorted when maximized. 
Priority | Medium Priority, Fatal to Operation
Severity | Medium
Screenshots | ![image](https://user-images.githubusercontent.com/48979024/112404364-9bd92c80-8ce6-11eb-8dc8-148fe779eb1a.png)

**Comment by Shawnli3287** [comment]
@mohful Thanks for this bug report. I (@Li-wenxuan-216374324 ) already fixed this bug.
