### ISSUE TITLE
wrong step note in some instances of double notes.

### ISSUE THREAD

**Issue by Yashraj-Rathore** [MaishaRahman98/demo2311#24]
**Bug by** -Yashraj Rathore

**Error name**- wrong step note in instances of double notes.

**Error Description-** when having double notes sometimes the wrong step note is being generated.

**Machine/Version**- Windows 10, Eclipse Gradle build

**Priority-medium** - priority

**Severity-medium**-  severity

**Reproduction**

1.	Run Application
2.	insert this guitar tablature [guitar2.txt](https://github.com/MaishaRahman98/demo2311/files/6201641/guitar2.txt).
3.	Translate the tablature.
**Expected Result**
 
![image](https://user-images.githubusercontent.com/46467096/112410058-f6778600-8cf0-11eb-9cd0-1c1d2d021697.png)

Actual Result

![image](https://user-images.githubusercontent.com/46467096/112410072-fc6d6700-8cf0-11eb-9791-f06f89f3c881.png)

**Comment by nugea** [comment]
Incorrect bug report, step should be G not C (string: 2, fret: 8).
