### ISSUE TITLE
Program Goes Loco when Resized

### ISSUE THREAD

**Issue by yasir720** [MaishaRahman98/demo2311#29]
Description: 
Resizing the program’s default window causes the program to behave sporadically.

Steps to Reproduce:
1. Open the program (following the steps outlined in the user manual)
2. Either resize the windows by length/width or hit the full screen button

Expected Result:
Ratio of program's window to stay consistent

Actual Result:
Everything goes crazy

Video Recording:
https://user-images.githubusercontent.com/60118527/112413604-dd71d380-8cf6-11eb-8628-305732528add.mp4

Machine/Version: 
Windows 10 Pro x64, Java 11, Eclipse Gradle Build, Latest Commit on Master Branch(ID: a0abf6c).

Priority: 
Minor - Program is still operational and will get the job done.

Severity: 
Moderate - Can be a big issue for those that will need to have the window shrinked or enlarged. Has the potential to be a severe issue for some users.

Input: 
N/A

MusicXML viewer used: 
https://opensheetmusicdisplay.github.io/demo/

**Comment by Shawnli3287** [comment]
@yasir720 Thanks for this bug report. I (@Li-wenxuan-216374324 ) already fixed this bug.

**Comment by Shawnli3287** [comment]
bug already fixed
