### ISSUE TITLE
Incorrect type of notes for guitar tablature

### ISSUE THREAD

**Issue by shawn-verma** [MaishaRahman98/demo2311#7]
Bug Raised By:
Shawn Verma

Version:
Master – last commit id a0abf6c

Platform:
Windows 10 x64

Description:
The type is found to be incorrect for guitar notes.

Details:
When interpreting an input guitar tablature, the notes are converted with incorrect type.

Reproduction:
1.	Run application
2.	Paste guitar tablature:
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|
3.	Click translate
4.	View resulting type tags in the generated musicxml

Expected:
For the first measure all notes should have a type of eighth.
For the second measure all notes should have a type of whole.

Actual:
For the first measure some notes are seen to have type of quarter.
For the second measure some notes are seen to have type of quarter.

Priority:
1

Severity:
High

Screenshots:
Input:
![image](https://user-images.githubusercontent.com/15975996/112250836-8275a900-8c30-11eb-9d17-6f88dc53dfb5.png)
Output:
measure 1:
![image](https://user-images.githubusercontent.com/15975996/112250939-b05aed80-8c30-11eb-91c7-2c51f00b6ac5.png)
measure 2:
![image](https://user-images.githubusercontent.com/15975996/112250889-9a4d2d00-8c30-11eb-8656-a57ab376463e.png)

Input file:
[input.txt](https://github.com/MaishaRahman98/demo2311/files/6194265/input.txt)

**Comment by nugea** [comment]
Issue fixed.
