### ISSUE TITLE
Incorrect alter of notes for guitar tablature

### ISSUE THREAD

**Issue by shawn-verma** [MaishaRahman98/demo2311#8]
Bug Raised By:
Shawn Verma

Version:
Master – last commit id a0abf6c

Platform:
Windows 10 x64

Description:
The alter is found to be incorrect for some guitar notes.

Details:
When interpreting an input guitar tablature, the note is converted with incorrect alter.

Reproduction:
1.	Run application
2.	Paste guitar tablature:
|-----------------|
|-----------------|
|-1---------------|
|-----------------|
|-----------------|
|-----------------|
3.	Click translate
4.	View resulting alter tag in the generated musicxml

Expected:
The note should have an alter of 1 in the generated musicxml

Actual:
The note has an alter of -1 in the generated musicxml

Priority:
Low

Severity:
Low

Screenshots:
Input:
![image](https://user-images.githubusercontent.com/15975996/112251850-5d823580-8c32-11eb-9bf1-769850ccc8fa.png)
Output:
![image](https://user-images.githubusercontent.com/15975996/112251879-6a068e00-8c32-11eb-9019-6495ece2a0da.png)

Input file:
[input.txt](https://github.com/MaishaRahman98/demo2311/files/6194258/input.txt)

**Comment by nugea** [comment]
Incorrect bug report, string 3 fret 1 is Ab (A flat).
